/**
 * Listing content for all five ad types.
 *
 * Conventions used throughout:
 *  - `seller`   references a `key` from seed/people.js
 *  - `daysAgo`  backdates createdAt/updatedAt so the catalogue has a believable
 *               posting history instead of every ad appearing in the same second
 *  - `inDays`   (events/offers) places the date in the future relative to seed time
 *  - prices are Kuwaiti Dinar and sit in the range these items actually sell for
 *    locally — a used Ford Expedition is 9,450 KD, a flat white is under 2 KD
 *  - `paymentMode` non-null marks a promoted/boosted listing
 */

const { IMG } = require("./images");

const PRODUCTS = [
  {
    seller: "gulftech",
    title: "iPhone 15 Pro Max 256GB — Natural Titanium",
    description:
      "Certified pre-owned, battery health 94%, no scratches on the screen or frame. Comes in the original box with an unused USB-C cable and our 6-month store warranty covering the board and battery. Face ID and both cameras tested in front of you before purchase. Trade-in accepted against your current phone.",
    images: [IMG.phoneA, IMG.phoneB, IMG.phoneC],
    category: "electronics",
    subCategory: "smartphones",
    quantity: 6,
    askingPrice: 210,
    discount: true,
    discountPercent: 10,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 3,
    paymentMode: "monthly",
  },
  {
    seller: "gulftech",
    title: "MacBook Air M3 13-inch — 16GB / 512GB",
    description:
      "Sealed 2024 model in Midnight, international warranty valid in Kuwait until next August. Ideal for design and development work — we can pre-install your software and migrate data from an old Mac at no charge. Student pricing available with a valid university ID.",
    images: [IMG.laptopA, IMG.laptopC, IMG.laptopB],
    category: "electronics",
    subCategory: "laptops",
    quantity: 4,
    askingPrice: 315,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 9,
  },
  {
    seller: "gulftech",
    title: "Sony WH-1000XM5 Noise Cancelling Headphones",
    description:
      "Industry-leading noise cancellation, 30-hour battery and multipoint pairing to your laptop and phone at the same time. Open box units — used only for in-store demo, cushions replaced, carry case and cable included. Two colours in stock: black and platinum silver.",
    images: [IMG.headphonesA, IMG.headphonesB],
    category: "electronics",
    subCategory: "headphones",
    quantity: 11,
    askingPrice: 92,
    discount: true,
    discountPercent: 15,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 16,
  },
  {
    seller: "gulftech",
    title: "Samsung 65\" QLED 4K Smart TV with Wall Mount",
    description:
      "2024 Q70D series with 120Hz panel and Dolby Atmos, perfect for the majlis or a gaming setup. Price includes delivery, wall mounting and cable management anywhere in Hawalli and Kuwait City. Old TV taken away free of charge on request.",
    images: [IMG.tvA, IMG.decorB],
    category: "electronics",
    subCategory: "accessories",
    quantity: 5,
    askingPrice: 195,
    discount: true,
    discountPercent: 12,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 24,
  },
  {
    seller: "fahaheel",
    title: "Samsung Galaxy S24 Ultra 512GB — Titanium Grey",
    description:
      "Dual SIM, one owner, always kept in a case with a screen protector from day one. Battery health report printed and attached to the box. S Pen included and fully functional. Viewing welcome at the shop on Fahaheel main street any day except Friday morning.",
    images: [IMG.androidA, IMG.androidB],
    category: "electronics",
    subCategory: "smartphones",
    quantity: 3,
    askingPrice: 235,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 5,
  },
  {
    seller: "fahaheel",
    title: "PlayStation 5 Slim Digital + 2 DualSense Controllers",
    description:
      "Barely used console from a closed gaming café, fully cleaned and tested for 12 hours under load. Includes two controllers, HDMI cable and a charging dock. Ask us about bundling FC 25 and a 12-month PS Plus card at a discount.",
    images: [IMG.consoleA],
    category: "electronics",
    subCategory: "accessories",
    quantity: 7,
    askingPrice: 148,
    discount: true,
    discountPercent: 8,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 12,
    paymentMode: "monthly",
  },
  {
    seller: "fahaheel",
    title: "iPad Air 11\" M2 128GB Wi-Fi + Apple Pencil Pro",
    description:
      "Bundle deal for students and designers. Tablet is in immaculate condition with under 40 charge cycles; the Pencil Pro is sealed. Comes with a magnetic folio case in your choice of colour and a free tempered glass fitting.",
    images: [IMG.tabletA, IMG.tabletB],
    category: "electronics",
    subCategory: "tablets",
    quantity: 4,
    askingPrice: 178,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 21,
  },
  {
    seller: "fahaheel",
    title: "DJI Mini 4 Pro — Fly More Combo",
    description:
      "Under 249g so no drone registration headaches for casual flying. Three batteries, ND filter set, shoulder bag and the RC 2 screen controller included. Firmware updated and geofencing configured for Kuwait airspace before handover.",
    images: [IMG.droneA, IMG.cameraB],
    category: "electronics",
    subCategory: "cameras",
    quantity: 2,
    askingPrice: 268,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 33,
  },
  {
    seller: "gulftech",
    title: "Canon EOS R6 Mark II Body + RF 24-105mm f/4L",
    description:
      "Professional full-frame kit with roughly 8,000 actuations, sensor cleaned and calibrated last month. Includes two genuine LP-E6NH batteries, a 128GB CFexpress card and a Peak Design strap. Perfect for wedding and event shooters starting out.",
    images: [IMG.cameraA, IMG.cameraB, IMG.photographerA],
    category: "electronics",
    subCategory: "cameras",
    quantity: 1,
    askingPrice: 745,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 41,
  },

  // ---- fashion ----
  {
    seller: "fatima",
    title: "Premium Nida Abaya Collection — Winter 2025",
    description:
      "Hand-finished abayas in heavyweight Japanese Nida fabric with subtle embroidered cuffs. Available in black, charcoal and deep navy, sizes 52 to 60. Free length alteration within three days of purchase. Matching sheila included with every piece.",
    images: [IMG.abayaA, IMG.clothingB],
    category: "fashion",
    subCategory: "clothing",
    quantity: 24,
    askingPrice: 38,
    discount: true,
    discountPercent: 20,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 7,
    paymentMode: "annually",
  },
  {
    seller: "fatima",
    title: "Leather Weekender Duffel — Handmade, Full Grain",
    description:
      "Vegetable-tanned full-grain leather that darkens beautifully with use. Fits a laptop plus two days of clothes, with a separate shoe compartment and a detachable shoulder strap. Monogramming in Arabic or English available for 3 KD extra.",
    images: [IMG.bagA, IMG.bagB],
    category: "fashion",
    subCategory: "bags",
    quantity: 9,
    askingPrice: 46,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 15,
  },
  {
    seller: "fatima",
    title: "18K Gold Freshwater Pearl Necklace — Certified",
    description:
      "AAA-grade 7.5mm freshwater pearls on an 18K yellow gold clasp, 45cm length. Supplied with a certificate of authenticity and a lined presentation box. Ideal as an engagement or graduation gift. Matching studs sold separately.",
    images: [IMG.jewelryA, IMG.jewelryB],
    category: "fashion",
    subCategory: "jewelry",
    quantity: 3,
    askingPrice: 340,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 28,
  },
  {
    seller: "layali",
    title: "Seiko Presage Cocktail Time — Automatic Dress Watch",
    description:
      "The blue 'Skydiving' dial that changes tone under different light. Automatic 4R35 movement with hand-winding and hacking, 40.5mm case, sapphire crystal. Bought last year, worn a handful of times, complete with box, papers and spare leather strap.",
    images: [IMG.watchB, IMG.watchA],
    category: "fashion",
    subCategory: "watches",
    quantity: 2,
    askingPrice: 152,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 19,
  },
  {
    seller: "gulftech",
    title: "Apple Watch Ultra 2 49mm — Titanium, Ocean Band",
    description:
      "Full titanium case with the Ocean Band and an extra Alpine Loop in the box. Depth gauge, dual-frequency GPS and the 3000-nit display that stays readable in Kuwait's summer sun. Battery health 100%, activation lock removed.",
    images: [IMG.smartwatchA, IMG.watchA],
    category: "fashion",
    subCategory: "watches",
    quantity: 3,
    askingPrice: 218,
    discount: true,
    discountPercent: 7,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 26,
  },
  {
    seller: "abdullah",
    title: "Nike Air Zoom Pegasus 41 — Men's Running Shoes",
    description:
      "Brand new in box, sizes 41 to 45 available. The everyday trainer most of the running group in Shaheed Park is wearing this season — ReactX foam and dual Air Zoom units. Bought a batch on a trip and selling the extras at cost.",
    images: [IMG.shoesA, IMG.shoesC, IMG.shoesB],
    category: "sports",
    subCategory: "shoes",
    quantity: 14,
    askingPrice: 32,
    discount: true,
    discountPercent: 22,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 11,
  },

  // ---- home ----
  {
    seller: "diwan",
    title: "3-Seater Velvet Sofa — Emerald Green, Solid Beech Frame",
    description:
      "Built in our Shuwaikh workshop from kiln-dried beech with high-density foam and a stain-resistant velvet. 210cm wide, legs available in brass or matte black. Choose from 60+ fabrics if emerald is not your colour — production takes 10 working days.",
    images: [IMG.sofaA, IMG.sofaB, IMG.decorA],
    category: "home",
    subCategory: "furniture",
    quantity: 6,
    askingPrice: 178,
    discount: true,
    discountPercent: 15,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 6,
    paymentMode: "annually",
  },
  {
    seller: "diwan",
    title: "Scandinavian Oak Dining Set — Table + 6 Chairs",
    description:
      "Solid white oak with a natural matte lacquer, 180cm extendable to 240cm for Ramadan gatherings. Chairs are upholstered in a boucle that wipes clean. Delivery, assembly and levelling included anywhere in Kuwait.",
    images: [IMG.kitchenB, IMG.decorB],
    category: "home",
    subCategory: "furniture",
    quantity: 4,
    askingPrice: 265,
    discount: false,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 18,
  },
  {
    seller: "diwan",
    title: "Handwoven Sadu Wall Tapestry — 120 x 80cm",
    description:
      "Woven on a traditional loom by a cooperative of Bedouin artisans, using the red, black and white geometry of classic Sadu work. Each piece is one of a kind and arrives with a hanging rod and a card naming the weaver.",
    images: [IMG.decorA, IMG.decorB],
    category: "home",
    subCategory: "decor",
    quantity: 12,
    askingPrice: 42,
    discount: false,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 34,
  },
  {
    seller: "diwan",
    title: "Industrial Arc Floor Lamp — Matte Black, Marble Base",
    description:
      "Adjustable 200cm arc that reaches over a sofa or reading chair, weighted Carrara marble base so it will not tip. Takes a standard E27 bulb; a warm-white smart bulb is included and pairs with Alexa or Google Home.",
    images: [IMG.lightingA, IMG.lightingB],
    category: "home",
    subCategory: "lighting",
    quantity: 15,
    askingPrice: 34,
    discount: true,
    discountPercent: 18,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 39,
  },
  {
    seller: "diwan",
    title: "LG 8kg Front Load Washing Machine — Inverter Direct Drive",
    description:
      "Energy-efficient inverter motor with a 10-year warranty on the motor itself, steam cycle and a 39-minute quick wash. Display supports Arabic and English. Price includes delivery, installation and removal of the old machine.",
    images: [IMG.washerA, IMG.fridgeA],
    category: "home",
    subCategory: "appliances",
    quantity: 8,
    askingPrice: 128,
    discount: true,
    discountPercent: 10,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 44,
  },
  {
    seller: "diwan",
    title: "Outdoor Rattan Seating Set with Weatherproof Cushions",
    description:
      "Four-piece set — two armchairs, a two-seater and a tempered glass coffee table. UV-stabilised PE rattan over an aluminium frame, so it survives a Kuwaiti summer on the roof or in the garden. Cushion covers are removable and machine washable.",
    images: [IMG.gardenB, IMG.gardenA],
    category: "home",
    subCategory: "garden",
    quantity: 5,
    askingPrice: 210,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 52,
  },
  {
    seller: "coral",
    title: "KitchenAid Artisan Stand Mixer 4.8L — Empire Red",
    description:
      "The workhorse we use for our own bakery trials. Includes the flat beater, dough hook and wire whisk plus a pouring shield. Lightly used display unit from the roastery, in perfect working order with the full manufacturer warranty card.",
    images: [IMG.kitchenA, IMG.kitchenC, IMG.bakeryA],
    category: "home",
    subCategory: "kitchen",
    quantity: 3,
    askingPrice: 155,
    discount: true,
    discountPercent: 12,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 29,
  },

  // ---- vehicles ----
  {
    seller: "yousef",
    title: "2021 Ford Expedition XLT 3.5L EcoBoost — Agency Maintained",
    description:
      "One owner from new, 78,000 km, full service history at the agency with every stamp in the book. Desert-ready with a roof rack and recovery points already fitted, and a fresh set of Toyo Open Country tyres. Seven seats, rear entertainment screens, registration valid until next March. No accidents, paint original throughout.",
    images: [IMG.suvDesertA, IMG.desertA],
    category: "vehicles",
    subCategory: "cars",
    quantity: 1,
    askingPrice: 9450,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 4,
    paymentMode: "monthly",
  },
  {
    seller: "yousef",
    title: "2022 Toyota Camry GLE 2.5L — Agency Warranty Remaining",
    description:
      "41,000 km with two years of agency warranty still to run. Single owner, non-smoker, serviced every 10,000 km at Al-Sayer. Cooled seats, wireless CarPlay and a 360-degree camera. Selling because I have imported a replacement; happy to arrange an independent inspection at any garage you choose.",
    images: [IMG.sedanA],
    category: "vehicles",
    subCategory: "cars",
    quantity: 1,
    askingPrice: 5850,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 13,
  },
  {
    seller: "yousef",
    title: "Ducati SuperSport 950 (2022) — 6,400 km",
    description:
      "Ducati Red with the Termignoni slip-on and a tail tidy already installed; original exhaust included for resale. Desmo service done at 12,000 km intervals, next one not due until 2027. Two keys, both fobs working. Serious buyers only.",
    images: [IMG.motorcycleB, IMG.motorcycleA],
    category: "vehicles",
    subCategory: "motorcycles",
    quantity: 1,
    askingPrice: 3350,
    discount: true,
    discountPercent: 5,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 22,
  },
  {
    seller: "yousef",
    title: "Genuine Toyota Service Parts Bundle — Filters, Belts & Plugs",
    description:
      "Full service kit for the 1GR-FE V6: oil filter, air filter, cabin filter, serpentine belt, six iridium plugs and a sump washer. All genuine parts bought for a vehicle I sold before the service was due. Boxes unopened, receipts included. Collection from Mangaf.",
    images: [IMG.carPartsB, IMG.carPartsA],
    category: "vehicles",
    subCategory: "parts",
    quantity: 4,
    askingPrice: 285,
    discount: false,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 37,
  },
  {
    seller: "abdullah",
    title: "Trek FX 3 Disc Hybrid Bike — Large Frame",
    description:
      "Aluminium frame with carbon fork and hydraulic disc brakes, ideal for the Gulf Road cycle track. Size L fits riders 178–188cm. Serviced last month with new brake pads and a fresh chain. Comes with lights, a bottle cage and a pannier rack.",
    images: [IMG.bicycleA, IMG.bicycleB, IMG.cyclingA],
    category: "vehicles",
    subCategory: "bicycles",
    quantity: 2,
    askingPrice: 185,
    discount: true,
    discountPercent: 10,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 31,
  },

  // ---- sports ----
  {
    seller: "abdullah",
    title: "Adjustable Dumbbell Set 2–24kg (Pair) with Stand",
    description:
      "Replaces fifteen pairs of dumbbells and takes up half a square metre — the answer to training in a Kuwaiti apartment. Dial adjustment in 2kg steps, rubberised plates that will not mark the floor, and a matching stand at working height.",
    images: [IMG.gymC, IMG.gymA],
    category: "sports",
    subCategory: "fitness",
    quantity: 10,
    askingPrice: 98,
    discount: true,
    discountPercent: 15,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 17,
  },
  {
    seller: "abdullah",
    title: "Padel Racket — Carbon Face, Diamond Shape + Cover",
    description:
      "Diamond-shaped 375g carbon racket for players who already have their technique and want more power at the net. Includes a padded cover and three tubes of pressurised balls. I coach at the Qurain courts most evenings if you want to demo it first.",
    images: [IMG.padelA, IMG.trackA],
    category: "sports",
    subCategory: "equipment",
    quantity: 12,
    askingPrice: 46,
    discount: false,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 25,
  },
  {
    seller: "layali",
    title: "Ray-Ban Aviator Classic — Polarised Green G-15",
    description:
      "Authentic Ray-Ban with the polarised G-15 lens that actually cuts the glare off the Gulf Road at 4pm. Gold frame, 58mm, complete with the case, cloth and authenticity card. Two units left from our accessories counter.",
    images: [IMG.clothingA, IMG.shoesB],
    category: "fashion",
    subCategory: "accessories",
    quantity: 6,
    askingPrice: 48,
    discount: true,
    discountPercent: 15,
    recurring: false,
    locationSameAsProfile: true,
    daysAgo: 46,
  },
  {
    seller: "littlesteps",
    title: "Montessori Wooden Learning Toys — Ages 3-6 Bundle",
    description:
      "Curated bundle of eight wooden activities we use in our own classrooms: shape sorter, counting rods, lacing beads, Arabic alphabet puzzle and more. Untreated beech with water-based paint, safe for little hands that end up in mouths.",
    images: [IMG.toysA, IMG.babyA],
    category: "home",
    subCategory: "decor",
    quantity: 18,
    askingPrice: 26,
    discount: true,
    discountPercent: 20,
    recurring: true,
    locationSameAsProfile: true,
    daysAgo: 20,
  },
];

const SERVICES = [
  {
    seller: "grace",
    title: "Deep Home Cleaning — Flats & Villas, Same Day Available",
    description:
      "Team of three with our own equipment and eco-friendly products. Covers kitchen degreasing, bathroom descaling, interior windows, skirting and inside cupboards on request. Two-bedroom flat takes around four hours. Fully insured and police-cleared staff.",
    images: [IMG.cleaningA, IMG.cleaningB],
    category: "home-services",
    subCategory: "cleaning",
    servicePrice: 28,
    serviceType: "cleaning",
    locationSameAsProfile: true,
    daysAgo: 2,
    paymentMode: "monthly",
  },
  {
    seller: "grace",
    title: "Post-Renovation & Move-In Cleaning",
    description:
      "The heavy one — cement dust, paint splatter, sticker residue and grout haze removed before you move furniture in. We bring industrial vacuums and floor polishers. Quoted per square metre after a free site visit anywhere in Hawalli.",
    images: [IMG.cleaningB, IMG.constructionA],
    category: "home-services",
    subCategory: "cleaning",
    servicePrice: 65,
    serviceType: "cleaning",
    locationSameAsProfile: true,
    daysAgo: 27,
  },
  {
    seller: "buildright",
    title: "Split & Central AC Servicing, Gas Refill and Repair",
    description:
      "Full service before the summer hits: coil wash, filter replacement, drain flush, gas pressure check and thermostat calibration. Central unit repairs handled by licensed technicians. Emergency call-outs answered within four hours, seven days a week.",
    images: [IMG.electricalB, IMG.plumbingB],
    category: "home-services",
    subCategory: "ac-repair",
    servicePrice: 18,
    serviceType: "repair",
    locationSameAsProfile: true,
    daysAgo: 5,
    paymentMode: "annually",
  },
  {
    seller: "buildright",
    title: "Emergency Plumbing — Leaks, Blockages & Water Heaters",
    description:
      "Burst pipes, blocked drains, running cisterns and dead water heaters. We carry the common parts on the van so most jobs finish in one visit. Camera inspection available for recurring blockages. Call-out fee waived if you proceed with the repair.",
    images: [IMG.plumbingA, IMG.plumbingB],
    category: "home-services",
    subCategory: "plumbing",
    servicePrice: 22,
    serviceType: "repair",
    locationSameAsProfile: true,
    daysAgo: 14,
  },
  {
    seller: "buildright",
    title: "Licensed Electrical Work — Rewiring, DBs and Lighting",
    description:
      "Distribution board upgrades, socket and switch installation, ceiling light and chandelier fitting, and fault finding on tripping circuits. All work done to Ministry of Electricity standards with a certificate issued on completion.",
    images: [IMG.electricalA, IMG.electricalB],
    category: "home-services",
    subCategory: "electrical",
    servicePrice: 25,
    serviceType: "installation",
    locationSameAsProfile: true,
    daysAgo: 23,
  },
  {
    seller: "buildright",
    title: "Interior Painting — Jotun Fenomastic, 2 Coats Included",
    description:
      "Priced per room including masking, minor filling, two coats of Jotun Fenomastic and a full clean-up. Colour consultation on WhatsApp before we start. A standard bedroom is done in a day; we work evenings if you cannot take time off.",
    images: [IMG.paintingB, IMG.paintingA],
    category: "home-services",
    subCategory: "painting",
    servicePrice: 45,
    serviceType: "technical",
    locationSameAsProfile: true,
    daysAgo: 36,
  },
  {
    seller: "buildright",
    title: "Custom Carpentry — Wardrobes, Kitchens and Majlis Units",
    description:
      "Made-to-measure joinery from our own workshop. Site survey, 3D drawing and a fixed quote before anything is cut. MDF, plywood or solid wood with soft-close hardware as standard. Typical wardrobe delivered and fitted in twelve days.",
    images: [IMG.carpentryB, IMG.carpentryA],
    category: "home-services",
    subCategory: "carpentry",
    servicePrice: 120,
    serviceType: "installation",
    locationSameAsProfile: true,
    daysAgo: 48,
  },
  {
    seller: "sadeeq",
    title: "Full Car Service — Oil, Filters and 40-Point Inspection",
    description:
      "Synthetic oil change, oil and air filter replacement, brake and suspension check, battery test and a written 40-point report with photos of anything that needs attention. Most cars finished in ninety minutes with a waiting area and Wi-Fi.",
    images: [IMG.carRepairA, IMG.carPartsA],
    category: "automotive",
    subCategory: "oil-change",
    servicePrice: 24,
    serviceType: "repair",
    locationSameAsProfile: true,
    daysAgo: 8,
    paymentMode: "monthly",
  },
  {
    seller: "sadeeq",
    title: "Computerised Diagnostics & Engine Fault Repair",
    description:
      "Warning light on and nobody can tell you why? We run manufacturer-level diagnostics on Japanese, German and American vehicles, then quote the actual fix — not a parts-swapping guess. Diagnostic fee deducted from the repair bill.",
    images: [IMG.carPartsA, IMG.carRepairA],
    category: "automotive",
    subCategory: "mechanical",
    servicePrice: 15,
    serviceType: "technical",
    locationSameAsProfile: true,
    daysAgo: 30,
  },
  {
    seller: "sadeeq",
    title: "Ceramic Coating & Paint Correction — 3 Year Protection",
    description:
      "Two-stage machine polish to remove swirls and light scratches, followed by a 9H ceramic coating that makes summer dust rinse straight off. Two-day job including interior detail. Includes a maintenance wash every three months for a year.",
    images: [IMG.carDetailA, IMG.carWashB],
    category: "automotive",
    subCategory: "detailing",
    servicePrice: 145,
    serviceType: "technical",
    locationSameAsProfile: true,
    daysAgo: 42,
  },
  {
    seller: "sadeeq",
    title: "Mobile Car Wash — We Come to Your Building",
    description:
      "Waterless and steam wash options for basement parking where hoses are not allowed. Exterior, wheels, interior vacuum and dashboard wipe-down in about forty minutes. Monthly packages for four washes work out considerably cheaper.",
    images: [IMG.carWashA, IMG.carWashB],
    category: "automotive",
    subCategory: "car-wash",
    servicePrice: 8,
    serviceType: "cleaning",
    locationSameAsProfile: true,
    daysAgo: 19,
  },
  {
    seller: "mariam",
    title: "Personal Training — Ladies Only, Home or Studio",
    description:
      "Certified NASM trainer with nine years' experience, specialising in post-natal recovery and strength for beginners. Sessions run 50 minutes, at your home, in your building gym or at my Salmiya studio. First consultation and movement screen are free.",
    images: [IMG.trainerA, IMG.pilatesA],
    category: "wellness",
    subCategory: "fitness-training",
    servicePrice: 18,
    serviceType: "fitness",
    locationSameAsProfile: true,
    daysAgo: 6,
    paymentMode: "monthly",
  },
  {
    seller: "mariam",
    title: "Private & Small Group Yoga — Vinyasa and Restorative",
    description:
      "Mixed-level vinyasa on weekday mornings and restorative sessions on Thursday evenings, capped at six people. Mats, blocks and straps provided. Beginners genuinely welcome — half my regulars had never done a downward dog before joining.",
    images: [IMG.yogaA, IMG.yogaB],
    category: "wellness",
    subCategory: "yoga",
    servicePrice: 12,
    serviceType: "fitness",
    locationSameAsProfile: true,
    daysAgo: 26,
  },
  {
    seller: "mariam",
    title: "Nutrition Coaching & Meal Planning — 8 Week Programme",
    description:
      "Eight weeks of structured coaching built around food you actually eat, including machboos, mandi and eating out with family. Weekly check-ins, a shopping list and macro targets adjusted as you progress. No banned foods and no meal-replacement shakes.",
    images: [IMG.nutritionA, IMG.nutritionB],
    category: "wellness",
    subCategory: "nutrition",
    servicePrice: 85,
    serviceType: "healthcare",
    locationSameAsProfile: true,
    daysAgo: 40,
  },
  {
    seller: "yasmeen",
    title: "Moroccan Hammam & Full Body Massage — 90 Minutes",
    description:
      "Traditional black soap scrub, ghassoul clay wrap and a steam session followed by a 45-minute aromatherapy massage. Private suites, female therapists only, and a herbal tea service afterwards. Bridal and mother-daughter packages available.",
    images: [IMG.massageA, IMG.spaA],
    category: "wellness",
    subCategory: "massage",
    servicePrice: 42,
    serviceType: "beauty",
    locationSameAsProfile: true,
    daysAgo: 10,
    paymentMode: "annually",
  },
  {
    seller: "yasmeen",
    title: "Hydrafacial & Skin Consultation — Dermatologist Approved",
    description:
      "Three-step cleanse, extract and hydrate protocol with a booster serum matched to your skin after a proper consultation. Visible results the same day with no downtime, which is why it books out before Eid. Course of three offered at a reduced rate.",
    images: [IMG.salonA, IMG.nailsA],
    category: "wellness",
    subCategory: "therapy",
    servicePrice: 35,
    serviceType: "beauty",
    locationSameAsProfile: true,
    daysAgo: 32,
  },
  {
    seller: "rohit",
    title: "Web Development — Next.js Sites & E-commerce Builds",
    description:
      "Full-stack developer building bilingual Arabic/English sites with proper RTL support, not a machine translation bolted on afterwards. Next.js, Node and MongoDB. Fixed-price project quotes, a staging link from week one and the source code is yours.",
    images: [IMG.webdevA, IMG.webdevB],
    category: "professional",
    subCategory: "web-development",
    servicePrice: 350,
    serviceType: "technical",
    locationSameAsProfile: true,
    daysAgo: 9,
    paymentMode: "monthly",
  },
  {
    seller: "rohit",
    title: "Brand Identity & Logo Design for Small Businesses",
    description:
      "Logo, colour palette, typography and a one-page brand guide, delivered in Arabic and Latin lockups so your signage and Instagram match. Three concepts, two rounds of revisions, and every source file handed over at the end.",
    images: [IMG.designA, IMG.designB],
    category: "professional",
    subCategory: "graphic-design",
    servicePrice: 180,
    serviceType: "creative",
    locationSameAsProfile: true,
    daysAgo: 24,
  },
  {
    seller: "rohit",
    title: "Bookkeeping & VAT-Ready Accounts for SMEs",
    description:
      "Monthly bookkeeping, invoice tracking and management accounts for small companies and freelancers in Kuwait. Cloud-based, so you can see your numbers any time instead of waiting for year end. Migration from spreadsheets handled free.",
    images: [IMG.accountingA, IMG.accountingB],
    category: "professional",
    subCategory: "accounting",
    servicePrice: 95,
    serviceType: "financial",
    locationSameAsProfile: true,
    daysAgo: 45,
  },
  {
    seller: "littlesteps",
    title: "IGCSE & SAT Preparation — Maths, Physics, Chemistry",
    description:
      "Small groups of four to six students with past-paper drilling and a diagnostic test before the first session so we target actual gaps. Tutors are practising teachers from British curriculum schools in Kuwait. Progress reports sent to parents fortnightly.",
    images: [IMG.tutoringA, IMG.tutoringB],
    category: "education",
    subCategory: "test-prep",
    servicePrice: 15,
    serviceType: "education",
    locationSameAsProfile: true,
    daysAgo: 12,
  },
  {
    seller: "littlesteps",
    title: "Arabic & French Language Classes — Kids and Adults",
    description:
      "Conversational Arabic for expat residents and structured French from beginner to DELF B2. Evening and weekend slots, in person in Bayan or online. Adults' classes are capped at eight so everyone actually gets to speak.",
    images: [IMG.languageA, IMG.tutoringB],
    category: "education",
    subCategory: "language-classes",
    servicePrice: 11,
    serviceType: "education",
    locationSameAsProfile: true,
    daysAgo: 21,
  },
  {
    seller: "littlesteps",
    title: "Piano & Oud Lessons — Beginner to Grade 5",
    description:
      "One-to-one lessons with a conservatory-trained teacher, following ABRSM for piano and traditional maqam study for oud. Instruments available at the centre for practice. End-of-term recital every June that the children genuinely look forward to.",
    images: [IMG.musicA, IMG.musicB],
    category: "education",
    subCategory: "music-lessons",
    servicePrice: 14,
    serviceType: "education",
    locationSameAsProfile: true,
    daysAgo: 38,
  },
  {
    seller: "tours",
    title: "Event Photography & Videography — Weddings and Corporate",
    description:
      "Two photographers and a video operator, full-day coverage with same-night sneak peeks and the edited gallery within two weeks. Drone footage included where permits allow. We shoot ladies-only sections with a female photographer on request.",
    images: [IMG.photographerA, IMG.cateringA],
    category: "professional",
    subCategory: "consulting",
    servicePrice: 250,
    serviceType: "creative",
    locationSameAsProfile: true,
    daysAgo: 16,
  },
  {
    seller: "grace",
    title: "Packing & Moving Service — Flats, Villas and Offices",
    description:
      "Boxes, bubble wrap and a team that disassembles and reassembles furniture at the other end. Insurance available for high-value items. Most two-bedroom moves within Kuwait finish inside a single day for a flat, agreed price.",
    images: [IMG.moversA, IMG.laundryA],
    category: "home-services",
    subCategory: "carpentry",
    servicePrice: 75,
    serviceType: "transport",
    locationSameAsProfile: true,
    daysAgo: 35,
  },
];

const EVENTS = [
  {
    seller: "coral",
    title: "Kuwait Specialty Coffee Festival 2026",
    description:
      "Three days of roasters, brew bars and latte art throwdowns at the Shuwaikh exhibition halls. Over forty local and regional roasters pouring, plus cupping tables where you can taste the same bean prepared six ways. Free entry before 4pm on the first day.",
    images: [IMG.coffeeA, IMG.cafeA, IMG.coffeeB],
    eventType: "festival",
    inDays: 24,
    eventTime: "16:00",
    endTime: "23:00",
    featuresAmenities: ["Free Parking", "Family Area", "Free Tastings", "Prayer Room", "Card Payments"],
    city: "kuwait-city",
    neighbourhood: "shuwaikh",
    daysAgo: 11,
    paymentMode: "annually",
  },
  {
    seller: "tours",
    title: "Failaka Island Heritage Day Trip",
    description:
      "Morning ferry from Ras Al-Ardh, guided walk through the Greek settlement at Ikaros and the abandoned village, lunch by the shore and free time to swim before the afternoon return. Bilingual guide, all permits arranged. Bring a hat and closed shoes.",
    images: [IMG.islandA, IMG.beachB, IMG.divingA],
    eventType: "other",
    inDays: 9,
    eventTime: "07:30",
    endTime: "17:00",
    featuresAmenities: ["Ferry Included", "Bilingual Guide", "Lunch Provided", "Small Group"],
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 6,
    paymentMode: "monthly",
  },
  {
    seller: "tours",
    title: "Kabd Desert Camping Weekend — Winter Season Opener",
    description:
      "Two nights under canvas in the Kabd reserve with traditional Bedouin tents, a fire pit, evening qahwa and a guided dune walk at sunrise. Sleeping bags and mattresses provided; you bring warm layers because the desert gets genuinely cold in December.",
    images: [IMG.desertA, IMG.grillA],
    eventType: "other",
    inDays: 52,
    eventTime: "15:00",
    endTime: "11:00",
    featuresAmenities: ["Tents Provided", "All Meals", "Campfire", "4x4 Transfer", "Separate Family Tents"],
    city: "jahra",
    neighbourhood: "al-jahra-city",
    daysAgo: 18,
  },
  {
    seller: "rohit",
    title: "Startup Q8 Founders Summit — Building for the Gulf",
    description:
      "A single-track day for founders and product people, with talks on payments, Arabic-first product design and raising in the GCC. Twelve speakers from Kuwait, Riyadh and Dubai, plus structured office hours where you can book fifteen minutes with an investor.",
    images: [IMG.conferenceA, IMG.conferenceB],
    eventType: "conference",
    inDays: 33,
    eventTime: "09:00",
    endTime: "18:00",
    featuresAmenities: ["Lunch Included", "Wi-Fi", "Recorded Sessions", "Investor Office Hours", "Free Parking"],
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 15,
    paymentMode: "annually",
  },
  {
    seller: "layali",
    title: "Arabic Calligraphy Workshop — Diwani Script for Beginners",
    description:
      "Four-hour introduction to Diwani with a working calligrapher. Qalam pens, ink and paper are provided and yours to keep, and you leave with a finished piece of your own name. No previous experience needed; the class is capped at twelve people.",
    images: [IMG.workshopA, IMG.galleryA],
    eventType: "workshop",
    inDays: 16,
    eventTime: "17:00",
    endTime: "21:00",
    featuresAmenities: ["Materials Included", "Small Group", "Certificate", "Refreshments"],
    city: "kuwait-city",
    neighbourhood: "mubarakiya",
    daysAgo: 8,
  },
  {
    seller: "abdullah",
    title: "Kuwait Padel Open — Amateur Doubles Championship",
    description:
      "Weekend doubles tournament across three categories, from first-timers to advanced. Round-robin group stage so every pair plays at least three matches. Prize money for the top category, medals for the rest, and the courts stay open for social play afterwards.",
    images: [IMG.padelA, IMG.trackA, IMG.ballA],
    eventType: "sports",
    inDays: 21,
    eventTime: "08:00",
    endTime: "22:00",
    featuresAmenities: ["Prizes", "Live Scoring", "Refreshments", "Spectator Seating", "Free Parking"],
    city: "mubarak-al-kabeer",
    neighbourhood: "qurain",
    daysAgo: 13,
    paymentMode: "monthly",
  },
  {
    seller: "nadi",
    title: "Gulf Road Charity Run — 5K and 10K",
    description:
      "Sunrise run along the corniche in aid of the Kuwait Children's Cancer Fund. Chip timing, water stations every 2.5km and a finisher's medal for everyone who crosses the line. Family walk category for those who would rather not race.",
    images: [IMG.trackA, IMG.footballA],
    eventType: "sports",
    inDays: 40,
    eventTime: "06:00",
    endTime: "10:00",
    featuresAmenities: ["Chip Timing", "Finisher Medal", "Water Stations", "Family Category", "Free T-Shirt"],
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 22,
  },
  {
    seller: "mandi",
    title: "Ramadan Ghabga Night — Live Grill & Oud Performance",
    description:
      "Late-night ghabga buffet with a live mandi and mixed grill station, traditional sweets and an oud player from 11pm. Family seating on the terrace and a separate hall for large groups. Reservations essential — last year we filled up two weeks ahead.",
    images: [IMG.arabicFoodA, IMG.grillA, IMG.restaurantB],
    eventType: "party",
    inDays: 61,
    eventTime: "21:30",
    endTime: "02:00",
    featuresAmenities: ["Live Music", "Buffet", "Family Section", "Valet Parking", "Group Bookings"],
    city: "farwaniya",
    neighbourhood: "khaitan",
    daysAgo: 26,
  },
  {
    seller: "diwan",
    title: "Kuwait Home & Interiors Expo",
    description:
      "Sixty exhibitors covering furniture, kitchens, lighting and smart home systems across two halls. Show-only pricing from most stands and free fifteen-minute consultations with interior designers on the hour. Bring your floor plan.",
    images: [IMG.exhibitionA, IMG.decorA, IMG.sofaB],
    eventType: "exhibition",
    inDays: 47,
    eventTime: "10:00",
    endTime: "22:00",
    featuresAmenities: ["Free Entry", "Show Discounts", "Design Consultations", "Café On Site", "Free Parking"],
    city: "kuwait-city",
    neighbourhood: "shuwaikh",
    daysAgo: 29,
  },
  {
    seller: "littlesteps",
    title: "Kids Science Discovery Day — Ages 6 to 12",
    description:
      "Hands-on stations covering rockets, slime chemistry, simple circuits and a planetarium dome. Children rotate in groups of ten with a facilitator, so parents can actually sit down for an hour. Includes a snack and a small take-home experiment kit.",
    images: [IMG.workshopB, IMG.toysA],
    eventType: "workshop",
    inDays: 12,
    eventTime: "10:00",
    endTime: "14:00",
    featuresAmenities: ["Supervised Activities", "Snack Included", "Take-Home Kit", "Parent Lounge", "Air Conditioned"],
    city: "hawalli",
    neighbourhood: "bayan",
    daysAgo: 7,
  },
  {
    seller: "yasmeen",
    title: "Bridal Beauty & Fashion Showcase",
    description:
      "Ladies-only evening featuring bridal makeup demonstrations, an abaya and gown runway from six Kuwaiti designers, and consultation booths for hair, skin and henna. Goodie bag for the first hundred guests and show-night pricing on all packages.",
    images: [IMG.clothingB, IMG.salonA, IMG.partyA],
    eventType: "exhibition",
    inDays: 28,
    eventTime: "18:00",
    endTime: "23:00",
    featuresAmenities: ["Ladies Only", "Goodie Bags", "Live Demos", "Refreshments", "Valet Parking"],
    city: "hawalli",
    neighbourhood: "mishref",
    daysAgo: 20,
    paymentMode: "monthly",
  },
  {
    seller: "gulftech",
    title: "Retro Gaming & Esports Night — FC 26 Tournament",
    description:
      "Sixty-four player knockout on FC 26 alongside a retro corner with original consoles from the nineties. Entry includes two hours of free play on the floor machines. Winner takes a PlayStation 5 bundle; runners-up get store vouchers.",
    images: [IMG.consoleA, IMG.partyB],
    eventType: "other",
    inDays: 19,
    eventTime: "17:00",
    endTime: "23:59",
    featuresAmenities: ["Prizes", "Free Play Area", "Snacks Available", "Air Conditioned", "Live Commentary"],
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 9,
  },
  {
    seller: "coral",
    title: "Jazz at the Marina — Open Air Concert",
    description:
      "Quartet playing standards and Arabic-jazz arrangements on the waterfront as the sun goes down. Seating is unreserved on the lawn, food trucks open from 6pm and the music runs until eleven. Bring a cushion; the grass is comfortable but not that comfortable.",
    images: [IMG.concertC, IMG.concertB, IMG.rooftopA],
    eventType: "concert",
    inDays: 36,
    eventTime: "19:00",
    endTime: "23:00",
    featuresAmenities: ["Open Air", "Food Trucks", "Family Friendly", "Free Seating", "Prayer Area"],
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 17,
  },
  {
    seller: "nadi",
    title: "Sunrise Beach Yoga & Breathwork Session",
    description:
      "Ninety minutes of gentle vinyasa and breathwork on the sand at Messilah before the heat arrives, finishing with a guided meditation as the sun clears the horizon. Mats provided. Suitable for complete beginners and free for club members.",
    images: [IMG.yogaB, IMG.beachA],
    eventType: "other",
    inDays: 5,
    eventTime: "05:30",
    endTime: "07:00",
    featuresAmenities: ["Mats Provided", "Beginner Friendly", "Ladies Section", "Free For Members"],
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 3,
  },
];

const OFFERS = [
  // ---- flash deals (24h expiry, set by the model's pre-save hook) ----
  {
    seller: "mandi",
    title: "Flash Deal: Family Mandi Tray for 6 — Today Only",
    description:
      "Whole lamb mandi tray with saffron rice, salad, dakkous and two litres of soft drink, enough for six adults. Available for dine-in, takeaway and delivery across Farwaniya. Order before 9pm — once the ovens are empty, they are empty.",
    images: [IMG.arabicFoodA, IMG.grillA, IMG.arabicFoodB],
    category: "restaurant",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 24,
    discountPercent: 35,
    loyaltyPoints: 120,
    daysAgo: 0,
  },
  {
    seller: "coral",
    title: "Flash Deal: Any Specialty Coffee + Croissant",
    description:
      "Pick any drink on the brew bar menu, from a cortado to a hand-poured Ethiopian, and pair it with a butter croissant straight out of the oven. Valid at the Salmiya roastery counter only, all day today.",
    images: [IMG.coffeeA, IMG.bakeryA, IMG.cafeB],
    category: "food",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 4.5,
    discountPercent: 40,
    loyaltyPoints: 60,
    daysAgo: 0,
  },
  {
    seller: "yasmeen",
    title: "Flash Deal: 60-Minute Aromatherapy Massage",
    description:
      "One of our therapists had a cancellation block open up today, so we are releasing the slots at a rate we normally only offer members. Private suite, female therapist, herbal tea afterwards. Booking required by phone.",
    images: [IMG.massageA, IMG.spaA],
    category: "spa",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 35,
    discountPercent: 45,
    loyaltyPoints: 150,
    daysAgo: 0,
  },
  {
    seller: "sadeeq",
    title: "Flash Deal: Full Car Wash & Interior Detail",
    description:
      "Exterior hand wash, wheel clean, interior vacuum, dashboard treatment and glass polish. Walk-ins accepted until 8pm today at the Al-Rai workshop, no appointment needed.",
    images: [IMG.carWashA, IMG.carDetailA],
    category: "services",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 12,
    discountPercent: 50,
    loyaltyPoints: 80,
    daysAgo: 0,
  },
  {
    seller: "nadi",
    title: "Flash Deal: 7-Day Full Gym & Pool Access Pass",
    description:
      "Full access to both training floors, all classes and the 25m pool for seven consecutive days, with an InBody scan on your first visit. Limited to fifty passes and they usually go within the hour.",
    images: [IMG.gymB, IMG.gymA],
    category: "fitness",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 20,
    discountPercent: 55,
    loyaltyPoints: 100,
    daysAgo: 0,
  },
  {
    seller: "layali",
    title: "Flash Deal: Custom 12ml Attar Blend",
    description:
      "Sit with our perfumer, describe the scent you want, and walk out with a bottle blended to it in under an hour. Today's price includes the engraved bottle we normally charge separately for.",
    images: [IMG.attarA, IMG.attarB],
    category: "shopping",
    flashDeal: true,
    discountDeal: true,
    claimDeal: true,
    fullPrice: 18,
    discountPercent: 40,
    loyaltyPoints: 90,
    daysAgo: 0,
  },

  // ---- standard offers ----
  {
    seller: "mandi",
    title: "Weekday Lunch: Chicken Mandi + Drink",
    description:
      "Quarter chicken mandi with rice, salad and a soft drink, served from noon to 4pm Sunday through Thursday. The lunch crowd from the Khaitan offices swears by it. Dine-in and takeaway both included.",
    images: [IMG.arabicFoodB, IMG.restaurantA],
    category: "restaurant",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 3.5,
    discountPercent: 25,
    expiryInDays: 45,
    loyaltyPoints: 40,
    daysAgo: 14,
    paymentMode: "monthly",
  },
  {
    seller: "mandi",
    title: "Free Dessert with Every Family Tray",
    description:
      "Order any family tray over 15 KD and the dessert is on us — a plate of hot luqaimat drizzled with date syrup, or a slice of kunafa nabulsiyah, whichever the table prefers. Applies to dine-in, takeaway and delivery, and there is no limit on how often you use it.",
    offerDetail: "Free luqaimat or kunafa with any family tray order over 15 KD",
    images: [IMG.dessertA, IMG.arabicFoodA],
    category: "restaurant",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 30,
    loyaltyPoints: 25,
    daysAgo: 21,
  },
  {
    seller: "coral",
    title: "Coffee Subscription — 2 Bags Monthly, 20% Off",
    description:
      "Two 250g bags of freshly roasted single-origin coffee delivered to your door every month, ground to your brew method or left as whole beans. Cancel any time, and every third month we slip in a bag from an experimental lot at no charge.",
    images: [IMG.coffeeB, IMG.cafeB],
    category: "food",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 14,
    discountPercent: 20,
    expiryInDays: 60,
    loyaltyPoints: 70,
    daysAgo: 25,
  },
  {
    seller: "coral",
    title: "Buy 5 Coffees, Get the 6th Free",
    description:
      "Collect a stamp on every drink you buy at the brew bar and the sixth one is free — any size, any method, including the single-origin pours that normally sit outside loyalty schemes. The card lives on your phone, so there is nothing to lose at the bottom of a bag.",
    offerDetail: "Digital loyalty card — 6th drink free, valid at all counters",
    images: [IMG.cafeA, IMG.coffeeA],
    category: "food",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 90,
    loyaltyPoints: 30,
    daysAgo: 38,
  },
  {
    seller: "yasmeen",
    title: "Bridal Package — Hammam, Facial, Hair & Makeup",
    description:
      "The full pre-wedding programme across two visits: Moroccan hammam and body polish in the first, then hydrafacial, hair styling and makeup on the day itself. Includes a trial session and a touch-up kit to take with you.",
    images: [IMG.salonA, IMG.spaA, IMG.nailsA],
    category: "spa",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 180,
    discountPercent: 30,
    expiryInDays: 75,
    loyaltyPoints: 250,
    daysAgo: 30,
    paymentMode: "annually",
  },
  {
    seller: "yasmeen",
    title: "Mother & Daughter Spa Afternoon",
    description:
      "Book any 60-minute treatment on a Sunday or Monday and a second guest is treated at no charge. Massage, facial or body polish, in adjoining suites so you are not separated. Herbal tea and a light plate are served afterwards in the relaxation lounge.",
    offerDetail: "Two-for-one on any 60-minute treatment, Sundays and Mondays",
    images: [IMG.spaA, IMG.massageA],
    category: "spa",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 40,
    loyaltyPoints: 110,
    daysAgo: 33,
  },
  {
    seller: "nadi",
    title: "Annual Membership — 3 Months Free",
    description:
      "Twelve months of full club access charged at nine, including all group classes, the pool, and a quarterly session with a coach to reset your programme. Freeze your membership for up to eight weeks a year if you travel over summer.",
    images: [IMG.gymA, IMG.pilatesA, IMG.gymC],
    category: "fitness",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 360,
    discountPercent: 25,
    expiryInDays: 55,
    loyaltyPoints: 300,
    daysAgo: 27,
    paymentMode: "annually",
  },
  {
    seller: "nadi",
    title: "Bring a Friend — Free Week for Both of You",
    description:
      "Refer someone who has never trained with us and you both get seven days of full club access — both training floors, every group class and the pool. There is no cap on referrals, and several of our members have not paid for a month since discovering that.",
    offerDetail: "Refer a friend and you both train free for seven days",
    images: [IMG.gymC, IMG.trainerA],
    category: "fitness",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 35,
    loyaltyPoints: 50,
    daysAgo: 41,
  },
  {
    seller: "gulftech",
    title: "Trade In Your Old Phone — Up to 60 KD Extra",
    description:
      "Bring any working smartphone from the last five years and we will value it on the spot against a new device, adding up to 60 KD over the standard trade-in book. Data transfer and old-device wiping are done in front of you.",
    images: [IMG.phoneB, IMG.phoneA],
    category: "shopping",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 60,
    discountPercent: 15,
    expiryInDays: 50,
    loyaltyPoints: 80,
    daysAgo: 19,
  },
  {
    seller: "fahaheel",
    title: "Free Screen Protector & Case with Any Phone",
    description:
      "Every phone we sell leaves the shop protected. Tempered glass fitted properly by hand with no dust or bubbles, plus a case from our standard range in the colour of your choice. Fitting takes ten minutes while we transfer your data across.",
    offerDetail: "Tempered glass fitted plus a case free with any phone purchase",
    images: [IMG.phoneC, IMG.tabletB],
    category: "shopping",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 65,
    loyaltyPoints: 35,
    daysAgo: 23,
  },
  {
    seller: "layali",
    title: "Oud & Bakhoor Gift Set — Eid Bundle",
    description:
      "A 12ml oud attar, 50g of premium bakhoor and a brass mabkhara presented in a lined wooden box. The gift we sell most of before Eid, and the one people come back for after they have given it once.",
    images: [IMG.attarB, IMG.jewelryB],
    category: "shopping",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 45,
    discountPercent: 25,
    expiryInDays: 44,
    loyaltyPoints: 90,
    daysAgo: 16,
  },
  {
    seller: "diwan",
    title: "Furnish a Majlis — 20% Off Complete Room Packages",
    description:
      "Order a full majlis set — seating, side tables, rug and lighting — and take twenty percent off the combined price, with free delivery, assembly and a design visit to check dimensions before anything is built.",
    images: [IMG.sofaB, IMG.decorA, IMG.lightingB],
    category: "shopping",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 850,
    discountPercent: 20,
    expiryInDays: 70,
    loyaltyPoints: 400,
    daysAgo: 35,
    paymentMode: "monthly",
  },
  {
    seller: "sadeeq",
    title: "Winter Service Package — Oil, Filters, AC Check",
    description:
      "Synthetic oil change, oil and air filter replacement, AC performance check and a full 40-point inspection with a photo report. Booked in ninety-minute slots so you are not sitting in the waiting room all morning.",
    images: [IMG.carRepairA, IMG.carPartsA],
    category: "services",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 32,
    discountPercent: 30,
    expiryInDays: 48,
    loyaltyPoints: 75,
    daysAgo: 28,
  },
  {
    seller: "tours",
    title: "Failaka Day Trip — Group of 4 Discount",
    description:
      "Book four seats on any Failaka Island departure and the fourth traveller goes free. Ferry, guide, permits and lunch are all included. Applies to weekday sailings, which are quieter and considerably more pleasant anyway.",
    images: [IMG.islandA, IMG.beachB],
    category: "travel",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 90,
    discountPercent: 25,
    expiryInDays: 58,
    loyaltyPoints: 180,
    daysAgo: 31,
  },
  {
    seller: "tours",
    title: "Desert Camping Weekend — Early Bird Rate",
    description:
      "Book any desert camping weekend at least three weeks ahead and save 20 KD per person. Same trip, same tents, same meals — just a better price for planning early, which also helps us size the camp properly. Applies to the full winter season.",
    offerDetail: "Book 3 weeks ahead and save 20 KD per person on any camp",
    images: [IMG.desertA, IMG.grillA],
    category: "travel",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 42,
    loyaltyPoints: 120,
    daysAgo: 37,
  },
  {
    seller: "littlesteps",
    title: "Term Enrolment — Second Sibling Half Price",
    description:
      "Enrol two children in the same term and the second pays half. Applies across tutoring, language classes and music lessons, and the siblings do not have to take the same subject or attend the same day. Assessment fees are waived for both.",
    offerDetail: "Enrol two children in the same term, second pays 50%",
    images: [IMG.tutoringA, IMG.workshopB],
    category: "services",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 36,
    loyaltyPoints: 60,
    daysAgo: 26,
  },
  {
    seller: "grace",
    title: "First Deep Clean — 30% Off for New Customers",
    description:
      "Try the full deep clean at nearly a third off if you have never booked with us. Three cleaners, our own equipment and eco-friendly products, covering kitchen, bathrooms, interior windows and inside cupboards on request.",
    images: [IMG.cleaningA, IMG.cleaningB],
    category: "services",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 28,
    discountPercent: 30,
    expiryInDays: 52,
    loyaltyPoints: 55,
    daysAgo: 12,
  },
  {
    seller: "buildright",
    title: "Annual AC Maintenance Contract — 2 Services Free",
    description:
      "Four scheduled services a year for the price of two, covering coil wash, filter replacement, drain flush and gas checks on up to six split units. Priority emergency response for contract holders during the summer months.",
    images: [IMG.electricalB, IMG.plumbingA],
    category: "services",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 120,
    discountPercent: 35,
    expiryInDays: 62,
    loyaltyPoints: 140,
    daysAgo: 24,
  },
  {
    seller: "mariam",
    title: "10-Session Personal Training Block",
    description:
      "Ten fifty-minute sessions booked as a block, at your home, your building gym or my Salmiya studio. Includes the movement screen, a written programme for the days we do not train together, and nutrition guidance throughout.",
    images: [IMG.trainerA, IMG.pilatesA],
    category: "fitness",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 180,
    discountPercent: 20,
    expiryInDays: 46,
    loyaltyPoints: 160,
    daysAgo: 20,
  },
  {
    seller: "abdullah",
    title: "Padel Court Booking — Off-Peak Hours",
    description:
      "Court hire before 4pm on weekdays comes in at 40% below the evening rate, and rackets are included so you can turn up with nothing but trainers. Courts are floodlit and covered, and the off-peak slots are genuinely quiet if you are still learning.",
    offerDetail: "40% off court hire before 4pm on weekdays, racket included",
    images: [IMG.padelA, IMG.ballA],
    category: "entertainment",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 38,
    loyaltyPoints: 45,
    daysAgo: 29,
  },
  {
    seller: "coral",
    title: "Weekend Brunch for Two — Rooftop Terrace",
    description:
      "Two brunch plates, two specialty drinks and a shared dessert on the terrace, Friday and Saturday from 9am to 1pm. The pancakes with date syrup are the reason the terrace fills up by ten, so book ahead.",
    images: [IMG.rooftopA, IMG.cafeA, IMG.dessertA],
    category: "restaurant",
    discountDeal: true,
    claimDeal: true,
    fullPrice: 16,
    discountPercent: 30,
    expiryInDays: 40,
    loyaltyPoints: 85,
    daysAgo: 18,
    paymentMode: "monthly",
  },
  {
    seller: "gulftech",
    title: "Laptop Bundle — Free Sleeve, Mouse & Setup",
    description:
      "Buy any laptop from us and we will add a padded sleeve and a wireless mouse, then set the machine up properly — Windows or macOS configured, updates installed and your data migrated from the old device before you leave the counter.",
    offerDetail: "Free sleeve, wireless mouse and data migration with any laptop",
    images: [IMG.laptopB, IMG.webdevB],
    category: "shopping",
    discountDeal: false,
    claimDeal: true,
    expiryInDays: 55,
    loyaltyPoints: 65,
    daysAgo: 32,
  },
];

const EXPLORES = [
  {
    seller: "tours",
    title: "Souq Al-Mubarakiya",
    exploreName: "Souq Al-Mubarakiya",
    description:
      "Kuwait City's oldest market and still its most alive corner after dark.",
    exploreDescription:
      "Two hundred years of trade compressed into a few covered lanes in the middle of Kuwait City. Spice merchants, gold dealers, perfume stalls and rows of dried limes sit alongside cafés where men have been arguing over the same tables for decades. Come after sunset when the temperature drops and the lanes fill — start at the fish and vegetable end, work your way through the textile arcade, and finish with tea and a plate of grilled meat at one of the open-air restaurants near the clock tower. Cash is still king with the smaller stalls, and haggling is expected rather than rude.",
    images: [IMG.souqB, IMG.spicesA, IMG.souqA],
    startTime: "09:00",
    endTime: "23:00",
    city: "kuwait-city",
    neighbourhood: "mubarakiya",
    daysAgo: 10,
    paymentMode: "annually",
  },
  {
    seller: "tours",
    title: "Al Shaheed Park",
    exploreName: "Al Shaheed Park",
    description:
      "Kuwait's largest urban park, built over the old city wall line.",
    exploreDescription:
      "Two hundred thousand square metres of landscaped walking trails, a botanical garden and two underground museums built along the line of the old city wall. The Habitat Museum covers Kuwait's desert and marine ecology; the Memorial Museum traces the country's modern history. Above ground there is a lake, an amphitheatre that hosts concerts through the cooler months, and a café terrace with a clear view of the Liberation Tower. Running and walking paths are lit until late, and the park is at its best between October and April.",
    images: [IMG.parkA, IMG.museumB],
    startTime: "08:00",
    endTime: "22:00",
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 15,
  },
  {
    seller: "tours",
    title: "Messilah Beach",
    exploreName: "Messilah Beach",
    description: "Wide, calm-water public beach on the southern coast.",
    exploreDescription:
      "A long stretch of soft sand with shallow, warm water that makes it one of the easier beaches for families with small children. Facilities include changing rooms, showers and a row of cafés set back from the sand. Weekday mornings are almost empty; Friday afternoons are the opposite. Shade structures cover part of the beach but bring your own umbrella if you plan to stay past noon. Swimming is comfortable from October through to June before the water gets too warm to be refreshing.",
    images: [IMG.beachA, IMG.beachB],
    startTime: "06:00",
    endTime: "20:00",
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 22,
  },
  {
    seller: "tours",
    title: "Failaka Island",
    exploreName: "Failaka Island",
    description:
      "Bronze Age settlement, Greek temple ruins and an abandoned village.",
    exploreDescription:
      "An hour by ferry from Ras Al-Ardh and a genuine step out of the city. Failaka holds the remains of Ikaros, a Greek settlement founded under Alexander's successors, alongside Bronze Age Dilmun sites and a village left exactly as it stood when residents evacuated in 1990. There is a small heritage village with restored houses, clear water for swimming on the northern shore, and very little shade — bring water, a hat and closed shoes for the ruins. Ferries run on a fixed timetable, so check the return sailing before you wander off.",
    images: [IMG.islandA, IMG.divingA, IMG.beachB],
    startTime: "07:00",
    endTime: "18:00",
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 28,
    paymentMode: "monthly",
  },
  {
    seller: "tours",
    title: "Kabd Desert Reserve",
    exploreName: "Kabd Desert Reserve",
    description: "Protected desert land, best at sunrise and in winter.",
    exploreDescription:
      "Forty minutes from the city and the landscape changes completely — low dunes, scrub and, after the winter rains, a brief carpet of wildflowers that draws photographers from across the country. The reserve is the traditional camping ground for Kuwaiti families through the cooler months, when tents go up across the area from November to March. Permits are required for overnight stays and the ground is soft in places, so a 4x4 and someone who knows the tracks are both strongly recommended.",
    images: [IMG.desertA, IMG.grillA],
    startTime: "05:00",
    endTime: "19:00",
    city: "jahra",
    neighbourhood: "al-jahra-city",
    daysAgo: 34,
  },
  {
    seller: "gulftech",
    title: "Salmiya Waterfront Promenade",
    exploreName: "Salmiya Waterfront Promenade",
    description: "Seafront walk, cafés and evening crowds along the Gulf Road.",
    exploreDescription:
      "The stretch of Gulf Road between Salmiya and Ras Al-Ardh is where Kuwait goes for an evening walk. A continuous paved promenade runs alongside the water with separate cycling lanes, exercise stations and small parks at intervals. Cafés and juice stands line the road opposite, and the marina end fills with families from around eight in the evening. Parking is straightforward on weekdays and difficult on Fridays. Sunset over the water from the northern end is the reason most people come.",
    images: [IMG.beachB, IMG.cafeA],
    startTime: "05:00",
    endTime: "23:59",
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 19,
  },
  {
    seller: "littlesteps",
    title: "Marine Life & Aquarium Centre",
    exploreName: "Marine Life & Aquarium Centre",
    description:
      "Gulf marine species, a walk-through tunnel and daily feeding shows.",
    exploreDescription:
      "Three connected habitats covering Kuwait's desert, sea and coastline, with the aquarium as the centrepiece — a walk-through tunnel where reef sharks and rays pass overhead, plus tanks devoted to the species of the Arabian Gulf specifically rather than the usual tropical selection. Feeding demonstrations run twice daily and the touch pool is supervised by staff who are genuinely good with nervous children. Allow two hours. Weekday mornings during term time are close to empty.",
    images: [IMG.aquariumA, IMG.fishA, IMG.divingA],
    startTime: "09:00",
    endTime: "21:00",
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 25,
  },
  {
    seller: "layali",
    title: "Contemporary Art Platform",
    exploreName: "Contemporary Art Platform",
    description:
      "Independent gallery in Shuwaikh showing Kuwaiti and regional artists.",
    exploreDescription:
      "A converted warehouse in the Shuwaikh industrial area that has become the centre of Kuwait's independent art scene. Exhibitions rotate roughly every six weeks and lean towards contemporary work from Kuwait, Iraq and the wider Gulf, with a permanent collection of regional modernists downstairs. There is a good art bookshop, a café, and an evening programme of talks and film screenings. Entry is free. The building is easy to miss from the road — look for the unmarked grey facade opposite the car showrooms.",
    images: [IMG.galleryA, IMG.museumA, IMG.exhibitionA],
    startTime: "10:00",
    endTime: "20:00",
    city: "kuwait-city",
    neighbourhood: "shuwaikh",
    daysAgo: 31,
  },
  {
    seller: "diwan",
    title: "Kuwait National Museum",
    exploreName: "Kuwait National Museum",
    description:
      "Archaeology, heritage and the restored Sadu House next door.",
    exploreDescription:
      "The national collection covers Failaka's Bronze Age and Hellenistic finds, Kuwait's pearl diving and dhow building traditions, and a heritage wing recreating daily life before oil. The planetarium in the same complex runs shows in Arabic and English. Next door, Sadu House preserves Bedouin weaving with a workshop where you can watch artisans at the loom and buy directly. The two together make a comfortable half day, and both sit within walking distance of the Seif Palace waterfront.",
    images: [IMG.museumA, IMG.museumB, IMG.decorA],
    startTime: "08:30",
    endTime: "19:00",
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 37,
  },
  {
    seller: "fahaheel",
    title: "Al Kout Waterfront, Fahaheel",
    exploreName: "Al Kout Waterfront, Fahaheel",
    description:
      "Seafront mall, dancing fountain and a traditional fish market.",
    exploreDescription:
      "Fahaheel's waterfront combines a modern mall with a working harbour and one of the better fish markets in the country, where the morning catch comes in off the boats moored a few metres away. The outdoor section has a dancing fountain that runs on the hour through the evening, restaurants along the water and a long promenade that stays busy until late. Come in the morning for the fish market and in the evening for everything else — the two crowds barely overlap.",
    images: [IMG.seafoodA, IMG.souqB, IMG.mallA],
    startTime: "09:00",
    endTime: "23:00",
    city: "ahmadi",
    neighbourhood: "fahaheel",
    daysAgo: 13,
  },
  {
    seller: "gulftech",
    title: "The Grand Retail Avenue",
    exploreName: "The Grand Retail Avenue",
    description:
      "Kuwait's largest indoor shopping district, laid out as themed streets.",
    exploreDescription:
      "A shopping centre built to feel like a series of streets rather than a single hall — a skylit boulevard of international brands, a souq-styled arcade of regional shops, and a district of restaurants with outdoor-style seating under a vaulted glass roof. There is a cinema complex, a large indoor play area for children and enough covered parking that even Thursday evening is manageable. Practically speaking it is where most of Kuwait spends the summer, when outdoor anything is unrealistic.",
    images: [IMG.mallA, IMG.shoppingA, IMG.cinemaA],
    startTime: "10:00",
    endTime: "23:59",
    city: "farwaniya",
    neighbourhood: "al-rai",
    daysAgo: 8,
    paymentMode: "monthly",
  },
  {
    seller: "coral",
    title: "Salmiya Coffee Lane",
    exploreName: "Salmiya Coffee Lane",
    description:
      "A single block with nine specialty roasteries and cafés.",
    exploreDescription:
      "Somewhere between 2018 and now, one block of Salmiya quietly became the centre of Kuwait's specialty coffee scene. Nine independent roasteries and cafés sit within a few minutes' walk of each other, most roasting on site, several running cupping sessions open to anyone who turns up. It is the best place in the country to taste your way through Ethiopian and Yemeni lots in an afternoon. Most open by eight in the morning and the later ones stay open past midnight.",
    images: [IMG.cafeB, IMG.coffeeA, IMG.bakeryA],
    startTime: "07:00",
    endTime: "01:00",
    city: "hawalli",
    neighbourhood: "salmiya",
    daysAgo: 5,
  },
  {
    seller: "abdullah",
    title: "Qurain Indoor Climbing Centre",
    exploreName: "Qurain Indoor Climbing Centre",
    description:
      "Bouldering and rope walls, air conditioned year round.",
    exploreDescription:
      "Fourteen metres of lead and top-rope walls plus a large bouldering room, with routes reset every fortnight so regulars do not get bored. Shoe and harness hire is included in the day pass and the introductory session covers belaying properly rather than in five rushed minutes. There is a ladies-only session on Monday and Wednesday evenings, a youth club on weekends, and a café upstairs with a view over the main wall.",
    images: [IMG.climbingA, IMG.gymC],
    startTime: "10:00",
    endTime: "23:00",
    city: "mubarak-al-kabeer",
    neighbourhood: "qurain",
    daysAgo: 17,
  },
  {
    seller: "littlesteps",
    title: "Winter Wonderland Family Park",
    exploreName: "Winter Wonderland Family Park",
    description:
      "Seasonal amusement park open through the cooler months.",
    exploreDescription:
      "A seasonal park that opens each November and runs until March, with around thirty rides split between a children's zone and a section for older visitors, plus carnival games, food stalls and a nightly light show. Wristbands cover unlimited rides and work out far cheaper than paying per ride once you are past the third one. Weeknights are calm; Thursday and Friday evenings are extremely busy and worth avoiding with small children.",
    images: [IMG.amusementA, IMG.partyB],
    startTime: "16:00",
    endTime: "23:59",
    city: "kuwait-city",
    neighbourhood: "shuwaikh",
    daysAgo: 26,
  },
  {
    seller: "mariam",
    title: "Jabriya Reading Room & Bookshop",
    exploreName: "Jabriya Reading Room & Bookshop",
    description:
      "Independent bookshop, quiet study floor and a small café.",
    exploreDescription:
      "An independent bookshop with a strong Arabic literature section, a decent English selection and a first floor set aside as a silent reading room with proper desks and power sockets. The café serves coffee that stands on its own merits rather than as an afterthought. Book club meets on the last Sunday of the month and there are occasional author evenings. It is one of the few places in Kuwait where you can work for four hours without anyone hurrying you along.",
    images: [IMG.libraryA, IMG.booksA],
    startTime: "09:00",
    endTime: "22:00",
    city: "hawalli",
    neighbourhood: "jabriya",
    daysAgo: 30,
  },
  {
    seller: "nadi",
    title: "Green Island",
    exploreName: "Green Island",
    description:
      "Man-made island off the Gulf Road with gardens and a small beach.",
    exploreDescription:
      "An artificial island connected to the Gulf Road by a short causeway, laid out with terraced gardens, an amphitheatre, a small artificial beach and a walking loop around the perimeter with clear views back to the city skyline. There is a modest entry fee, a couple of cafés and enough shade to make an afternoon visit realistic in spring. Best visited an hour before sunset, when the light on the towers across the bay is worth the walk on its own.",
    images: [IMG.gardenB, IMG.beachB, IMG.parkA],
    startTime: "08:00",
    endTime: "22:00",
    city: "kuwait-city",
    neighbourhood: "sharq",
    daysAgo: 21,
  },
];

module.exports = { PRODUCTS, SERVICES, EVENTS, OFFERS, EXPLORES };
