/**
 * Engagement content: review copy, chat conversations and notification wording.
 *
 * Reviews are written per ad type rather than generated, because generic praise
 * ("Great product! 5 stars") is the tell that a marketplace is running on dummy
 * data. Ratings are deliberately not all fives — a listing with 4.6 and one
 * lukewarm three-star review reads as real, a wall of fives does not.
 */

// Each entry: [rating, text]
const REVIEWS = {
  product: [
    [5, "Exactly as described. Met the seller at their shop in Salmiya, everything was tested in front of me before I paid. Would buy from them again."],
    [5, "Honest seller and a fair price. He pointed out a small scuff himself before I even noticed it, which says a lot."],
    [4, "Good condition and it works perfectly. Took two days longer to arrange the meeting than I hoped, but no complaints about the item itself."],
    [5, "Been using it for three weeks now with no issues at all. Battery lasts the full day. Very happy with the purchase."],
    [4, "Item is genuine and the price was better than the mall. Packaging was a bit rough but the product itself is fine."],
    [5, "Fast replies on chat, sent me extra photos when I asked, and delivered to Jabriya the same evening. Smooth from start to finish."],
    [3, "The product is fine but the photos make it look newer than it is. Still usable and the price reflects the condition, so I am not unhappy."],
    [5, "Second time buying from this seller. Same standard both times — genuine items and no games with the price."],
    [4, "Delivered on time and well packed. Would have liked the accessories mentioned in the description to be included, but the seller sorted it out after I asked."],
    [5, "Quality is much better than I expected for the price. My wife has already asked me to order a second one."],
    [5, "Very professional. Gave me a printed warranty card and registered it under my name without me having to ask."],
    [4, "Solid product, works as advertised. Only note is that delivery to Ahmadi cost extra, which was not obvious from the listing."],
    [5, "Bought as a gift and it arrived beautifully presented. The seller even included a handwritten note."],
    [4, "Happy overall. Slight delay because the colour I wanted was out of stock, but they called me the moment it came in."],
    [5, "Genuinely surprised by the condition — looks brand new. Whoever refurbished this knew what they were doing."],
    [3, "Does the job but the finish is not as premium as the pictures suggest. Fine for the money, just manage your expectations."],
    [5, "Great communication throughout and they honoured the discount they advertised without me having to remind them."],
    [4, "Good value. Assembly took longer than the listing said, but the instructions were clear enough."],
    [5, "Perfect for what I needed. The seller answered my questions honestly instead of just trying to close the sale."],
    [5, "Ordered on a Thursday and had it by Saturday. Excellent service, no notes."],
  ],
  service: [
    [5, "Turned up on time, worked cleanly and left the place tidier than they found it. Booking them again next month."],
    [5, "Fixed a leak two other plumbers had failed to find. Charged what he quoted and did not invent extra problems."],
    [4, "Good work and reasonable pricing. Communication before the appointment could be a bit clearer, but the job itself was done properly."],
    [5, "Very professional team. They explained what they were doing at each stage and sent photos of the finished work."],
    [5, "Best decision I made this year. Six weeks in and the difference is obvious. Genuinely knows what they are talking about."],
    [4, "Happy with the result. They ran about forty minutes late but called ahead to let me know, which I appreciated."],
    [5, "Quoted a fixed price, stuck to it, and finished a day early. That almost never happens."],
    [3, "The work was fine but I had to follow up twice to get the invoice. Would use again for the quality, not for the admin."],
    [5, "Polite, punctual and thorough. My mother is difficult to please and even she was impressed."],
    [5, "They came out on a Friday evening for an emergency and did not charge a premium for it. Saved us from a flooded kitchen."],
    [4, "Solid service and fair pricing. The team was efficient and respectful of the house."],
    [5, "Been using them for our office for the past year. Consistent every single visit, which is what actually matters."],
    [5, "Really took the time to understand what I wanted before starting. The result is better than what I had pictured."],
    [4, "Good quality work. Slightly more expensive than other quotes I got, but you can see where the money went."],
    [5, "Answered my questions on chat for two days before I even booked, with no pressure at all. That is why I chose them."],
    [3, "Decent job overall, though a couple of small details needed a second visit to correct. To their credit, they came back without arguing."],
    [5, "Discreet, professional and genuinely skilled. I have already recommended them to three neighbours."],
    [5, "Flexible with timings around my work schedule, which no one else was willing to do."],
    [4, "Very happy with the outcome. The follow-up advice afterwards was a nice touch."],
    [5, "Transparent pricing, no surprises on the final bill, and the quality speaks for itself."],
  ],
  event: [
    [5, "Really well organised. Started on time, the signage was clear and the staff actually knew what was going on."],
    [4, "Enjoyable evening. Parking was a challenge but the event itself was worth the walk."],
    [5, "Took the whole family and everyone found something they liked. The kids are already asking about next year."],
    [5, "Better than I expected for the ticket price. The speakers were substantive rather than just promotional."],
    [4, "Good atmosphere and a decent turnout. Food options ran out a bit early which was the only real letdown."],
    [5, "The venue was perfect and the crowd was friendly. One of the better evenings out I have had in Kuwait."],
    [5, "Well run from registration to close. The organisers clearly put thought into how people move through the space."],
    [3, "Interesting content but it overran by nearly an hour and the seating was uncomfortable by the end."],
    [5, "Loved it. The family section meant we could actually relax rather than watching the kids the whole time."],
    [4, "Great value for what was included. Would have liked more shade in the outdoor area."],
    [5, "Booked on the platform in two minutes and the QR code worked straight away at the gate. Painless."],
    [5, "The workshop was small enough that everyone got individual attention. Left with something I was proud of."],
    [4, "Solid event. Clear communication by WhatsApp beforehand about timings and what to bring."],
    [5, "Sunrise start was worth losing the sleep for. Beautifully organised and genuinely calming."],
  ],
  offer: [
    [5, "Claimed the deal, showed the code at the counter, no questions asked. Exactly how it should work."],
    [5, "Excellent value. We would have paid full price happily, so this was a bonus."],
    [4, "Good deal and easy to redeem. The staff had to check with a manager first but it went through fine."],
    [5, "Used this three times now. The discount applies without fuss every single time."],
    [5, "Genuinely a saving, not one of those fake discounts where they raise the price first."],
    [4, "Happy with it. Worth noting the offer does not apply on Fridays, which was not obvious to me."],
    [5, "Claimed it on my phone while standing in the queue and it worked immediately. Very smooth."],
    [3, "The deal itself is good but the branch was busy and we waited a while. Worth it in the end."],
    [5, "Loyalty points came through instantly and pushed me over into Silver. Nice touch."],
    [5, "Best offer I have claimed on here so far. Told two colleagues about it the same day."],
    [4, "Straightforward and honest. The terms were clearly stated up front with no hidden conditions."],
    [5, "Fast redemption and friendly staff who clearly knew about the platform promotion."],
    [5, "Flash deal was gone within an hour, so glad I claimed it when I saw the notification."],
    [4, "Good discount. Would be even better if it could be used for delivery orders too."],
  ],
  explore: [
    [5, "Went on a weekday evening and had the place almost to ourselves. Genuinely worth the trip."],
    [5, "One of those spots you keep meaning to visit and then wonder why you waited so long."],
    [4, "Beautiful, though it gets crowded after sunset. Go earlier if you want photos without people in them."],
    [5, "Took visiting family here and they talked about it for the rest of the trip. Very proud to show it off."],
    [5, "The description here was accurate, which is more than I can say for most listings. Timings were correct too."],
    [4, "Lovely place. Facilities could use some maintenance but that does not take away from the setting."],
    [5, "Perfect for an afternoon out with kids. Plenty of space and enough shade to survive a warm day."],
    [3, "Nice enough but smaller than I imagined from the photos. Still a pleasant hour or so."],
    [5, "Best at sunset, exactly as the listing said. Bring a camera and stay for the light."],
    [5, "Been coming here for years and it never gets old. Good to see it finally listed properly online."],
    [4, "Easy to find, parking was straightforward, and the walk around the whole site took about ninety minutes."],
    [5, "Really well kept. The staff were helpful and there was no pressure to spend money to be there."],
    [5, "Quiet, uncrowded and genuinely interesting. A rare combination."],
    [4, "Worth a visit. Go on a weekday if you can — weekends are a completely different experience."],
  ],
};

/**
 * Chat threads. `seller`/`buyer` reference a people.js key or buyer email;
 * `ad` matches a listing title so a real product reference card can be attached.
 */
const CHATS = [
  {
    seller: "gulftech",
    buyer: "ali.albaghli@gmail.com",
    ad: "iPhone 15 Pro Max 256GB — Natural Titanium",
    hoursAgo: 3,
    unread: 1,
    messages: [
      { from: "buyer", text: "Salam, is the iPhone still available?", withProductRef: true },
      { from: "seller", text: "Wa alaikum salam. Yes, we have two units left in Natural Titanium." },
      { from: "buyer", text: "What is the actual battery health? The listing says 94%." },
      { from: "seller", text: "94% on both. I can send you a screenshot of the battery page now.", images: 1 },
      { from: "buyer", text: "Perfect. Is the 10% discount still applied at that price?" },
      { from: "seller", text: "Yes, 189 KD after discount. That includes the tempered glass fitted in store." },
      { from: "buyer", text: "Great. Can I come tomorrow around 6pm?" },
      { from: "seller", text: "Of course. We are on Salem Al Mubarak Street, opposite the Marina entrance.", location: true },
      { from: "buyer", text: "Found it on the map, see you tomorrow inshallah." },
    ],
  },
  {
    seller: "yousef",
    buyer: "nasser.hammadi@gmail.com",
    ad: "2021 Ford Expedition XLT 3.5L EcoBoost — Agency Maintained",
    hoursAgo: 9,
    unread: 0,
    messages: [
      { from: "buyer", text: "Is the Expedition still for sale?", withProductRef: true },
      { from: "seller", text: "Yes, still available. 78,000 km, full agency history." },
      { from: "buyer", text: "Any accidents? And is the paint original all around?" },
      { from: "seller", text: "No accidents, paint is original on every panel. You are welcome to bring it to any garage for inspection before you decide." },
      { from: "buyer", text: "That is fair. Would you accept 11,800?" },
      { from: "seller", text: "I can do 12,200 with the roof rack and snorkel included. That is the best I can do." },
      { from: "buyer", text: "Let me speak to my brother and come back to you this evening." },
      { from: "seller", text: "No problem, take your time. I will let you know if anyone else puts a deposit down." },
    ],
  },
  {
    seller: "grace",
    buyer: "hessa.mansour@gmail.com",
    ad: "Deep Home Cleaning — Flats & Villas, Same Day Available",
    hoursAgo: 26,
    unread: 2,
    messages: [
      { from: "buyer", text: "Hi, do you cover Rumaithiya? I need a deep clean for a 3-bedroom flat." },
      { from: "seller", text: "Yes we do. For a 3-bedroom it is usually 35 KD and takes about five hours with a team of three." },
      { from: "buyer", text: "Does that include inside the kitchen cupboards and the balcony?" },
      { from: "seller", text: "Inside cupboards yes, balcony we charge 5 KD extra if it needs pressure washing." },
      { from: "buyer", text: "Understood. Are you available this Saturday morning?" },
      { from: "seller", text: "Saturday 9am is open. Shall I book it for you?" },
      { from: "seller", text: "Also, we bring our own equipment and products, so you do not need to prepare anything." },
    ],
  },
  {
    seller: "diwan",
    buyer: "shaikha.qattan@outlook.com",
    ad: "3-Seater Velvet Sofa — Emerald Green, Solid Beech Frame",
    hoursAgo: 48,
    unread: 0,
    messages: [
      { from: "buyer", text: "Is the emerald velvet the only option, or can I choose another fabric?", withProductRef: true },
      { from: "seller", text: "You can choose from over 60 fabrics at no extra cost. I can send the swatch catalogue if you like." },
      { from: "buyer", text: "Yes please, I am looking for something in a warm beige." },
      { from: "seller", text: "Here are the closest three from our current stock.", images: 2 },
      { from: "buyer", text: "The middle one is lovely. How long for production?" },
      { from: "seller", text: "Ten working days from confirmation, then delivery and assembly included." },
      { from: "buyer", text: "And the 15% discount applies to custom fabric as well?" },
      { from: "seller", text: "Yes, same price. 151 KD delivered and assembled." },
      { from: "buyer", text: "Wonderful, I will confirm with my husband tonight and message you." },
    ],
  },
  {
    seller: "mariam",
    buyer: "anjali.nair.kw@gmail.com",
    ad: "Personal Training — Ladies Only, Home or Studio",
    hoursAgo: 5,
    unread: 1,
    messages: [
      { from: "buyer", text: "Hello! I have not trained in about four years and I am nervous about starting again. Do you work with complete beginners?" },
      { from: "seller", text: "Most of my clients start exactly where you are. The first session is just a movement screen and a chat, no training at all." },
      { from: "buyer", text: "That is reassuring. Do you come to buildings in Salmiya?" },
      { from: "seller", text: "Yes, I cover Salmiya, Jabriya and Rumaithiya. If your building gym has dumbbells and a mat, that is enough to start." },
      { from: "buyer", text: "It does. What are the timings you have free?" },
      { from: "seller", text: "I have 7am and 6:30pm slots open on Sunday, Tuesday and Thursday. The 10-session block works out at 14.4 KD per session." },
    ],
  },
  {
    seller: "coral",
    buyer: "omar.farouk88@gmail.com",
    ad: "Coffee Subscription — 2 Bags Monthly, 20% Off",
    hoursAgo: 72,
    unread: 0,
    messages: [
      { from: "buyer", text: "Can I choose which origins come in the subscription, or is it a surprise?" },
      { from: "seller", text: "You can set a preference — fruity, chocolatey or balanced — and we pick within that. Most people enjoy not knowing exactly what is coming." },
      { from: "buyer", text: "I will go with fruity. Do you grind for AeroPress?" },
      { from: "seller", text: "We do. Just note it on the order and we grind fresh on roast day." },
      { from: "buyer", text: "Subscribed. Looking forward to the first bag." },
      { from: "seller", text: "Shukran! Roasting is on Sunday, so yours will be delivered Monday or Tuesday." },
    ],
  },
  {
    seller: "sadeeq",
    buyer: "talal.zamel@outlook.com",
    ad: "Computerised Diagnostics & Engine Fault Repair",
    hoursAgo: 14,
    unread: 1,
    messages: [
      { from: "buyer", text: "My check engine light came on yesterday. 2019 BMW 530i. Two garages told me different things." },
      { from: "seller", text: "Bring it in and we will read the actual fault codes rather than guess. Diagnostic is 15 KD and we deduct it if you do the repair with us." },
      { from: "buyer", text: "Do you need an appointment or can I come directly?" },
      { from: "seller", text: "Mornings before 10 are usually quiet, you can come directly. We are in Al-Rai behind the auto spare parts market.", location: true },
      { from: "buyer", text: "I will come tomorrow morning then. Thank you." },
      { from: "seller", text: "See you then. Bring the registration book if you have it." },
    ],
  },
  {
    seller: "tours",
    buyer: "priya.venkatesh@gmail.com",
    ad: "Failaka Island Heritage Day Trip",
    hoursAgo: 30,
    unread: 0,
    messages: [
      { from: "buyer", text: "Is the Failaka trip suitable for a 7 year old?", withProductRef: true },
      { from: "seller", text: "Yes, we take families every week. The walking is about 3km total across the day with breaks, and there is swimming time in the afternoon." },
      { from: "buyer", text: "Is there shade at the ruins?" },
      { from: "seller", text: "Very little, honestly. Bring hats and we provide water throughout. We schedule the ruins for the morning before it gets hot." },
      { from: "buyer", text: "Good to know. Booking three seats for the trip in two weeks." },
      { from: "seller", text: "Perfect. With three seats you are close to the group-of-four offer, in case a friend wants to join." },
    ],
  },
  {
    seller: "layali",
    buyer: "reem.darwish@gmail.com",
    ad: "Oud & Bakhoor Gift Set — Eid Bundle",
    hoursAgo: 55,
    unread: 0,
    messages: [
      { from: "buyer", text: "I need eight of these as corporate gifts. Is there a bulk price?" },
      { from: "seller", text: "For eight sets I can do 30 KD each instead of the offer price, and we will include printed gift cards." },
      { from: "buyer", text: "Can the boxes be engraved with our company name?" },
      { from: "seller", text: "Yes, engraving adds two days and 2 KD per box. Here is how it looks on a previous order.", images: 1 },
      { from: "buyer", text: "That looks excellent. Let us proceed with eight engraved." },
      { from: "seller", text: "Noted. I will send the invoice on WhatsApp and they will be ready by Wednesday." },
    ],
  },
  {
    seller: "buildright",
    buyer: "meshal.rasheed@gmail.com",
    ad: "Split & Central AC Servicing, Gas Refill and Repair",
    hoursAgo: 2,
    unread: 1,
    messages: [
      { from: "buyer", text: "One of my split units is blowing warm air. Can someone come today?" },
      { from: "seller", text: "We can be there within four hours. Which area are you in?" },
      { from: "buyer", text: "Qurain, block 4." },
      { from: "seller", text: "Technician will be with you between 2 and 4pm. If it is a gas refill it is 18 KD, if the compressor has gone we will quote before touching anything." },
    ],
  },
];

/**
 * Notification templates. `{title}` is replaced with the ad title and
 * `{seller}` with the seller's display name at seed time.
 */
const NOTIFICATION_TEMPLATES = {
  NEW_FLASH_DEAL: {
    title: "Flash deal live now",
    message: "{seller} just launched a flash deal — {title}",
    description: "Flash deals expire 24 hours after they go live. Claim yours before it disappears.",
    tags: ["flash", "limited-time"],
  },
  FLASH_DEAL_ENDING_SOON: {
    title: "Ending in a few hours",
    message: "Last chance on {title}",
    description: "This flash deal expires today. Claim your code now to lock in the price.",
    tags: ["flash", "ending-soon"],
  },
  DEAL_IN_YOUR_AREA: {
    title: "New deal near you",
    message: "{seller} posted a new offer in your area — {title}",
    description: "Deals from sellers in your neighbourhood, so you are not driving across Kuwait to redeem them.",
    tags: ["nearby", "offer"],
  },
  NEW_AD: {
    title: "New listing in your area",
    message: "{seller} just posted {title}",
    description: "A new listing went live near you.",
    tags: ["nearby", "new"],
  },
  PRICE_DROP: {
    title: "Price drop on a saved item",
    message: "{title} is now cheaper than when you saved it",
    description: "One of your wishlist items has come down in price.",
    tags: ["wishlist", "price-drop"],
  },
  OUT_OF_STOCK: {
    title: "Almost gone",
    message: "{title} is running low on stock",
    description: "An item on your wishlist is nearly sold out.",
    tags: ["wishlist", "stock"],
  },
  ORDER_UPDATE: {
    title: "Claim confirmed",
    message: "Your claim code for {title} is ready",
    description: "Show the code or QR at the counter to redeem your offer.",
    tags: ["claim", "wallet"],
  },
};

const NEWSLETTER_EXTRA = [
  "sara.khoury@gmail.com",
  "abdulaziz.alhamad@gmail.com",
  "nadia.suleiman@outlook.com",
  "ravi.krishnan.kw@gmail.com",
  "maha.alqallaf@gmail.com",
  "peter.almeida@gmail.com",
  "huda.alshatti@outlook.com",
  "mustafa.rahman.kw@gmail.com",
  "leen.abdulwahab@gmail.com",
  "chris.mathew.q8@gmail.com",
  "fatima.zahra@outlook.com",
  "yaqoub.alsalem@gmail.com",
  "rania.ghanem@gmail.com",
  "sunil.thomas.kw@gmail.com",
  "amal.alkhaldi@gmail.com",
];

module.exports = { REVIEWS, CHATS, NOTIFICATION_TEMPLATES, NEWSLETTER_EXTRA };
